services:
  notebook:
    image: quay.io/jupyter/minimal-notebook
    command: start-notebook.py --IdentityProvider.token=''
    ports:
      - 8888:8888
    volumes:
      - ./notebook-files:/home/jovyan/work
      - ./openai-key.txt:/home/jovyan/work/openai-key.txt

  pdf-bot:
    build: ./pdf-bot
    ports:
      - 8080:8080
    volumes:
      - ./pdf-bot:/usr/local/app
      - ./openai-key.txt:/openai-key.txt
    environment:
      OPENAI_KEY_FILE: /openai-key.txt

  neo4j:
    user: neo4j:neo4j
    image: neo4j:5.11
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_db_tx__log_rotation_retention__policy=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    healthcheck:
        test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
        interval: 15s
        timeout: 30s
        retries: 10

volumes:
  neo4j-data: